# Handling Reading
encoding:     "utf-8"
markdown_ext: "md"

# Conversion
markdown:    redcarpet
highlighter: pygments

# Outputting
defaults:
  -
    scope:
      path: "documents"
      type: "pages"
    values:
      layout: "documents"
      author: "CODEYA"
      category: "documents"

# Markdown Processors
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
